# Generated by Django 6.0.8 on 2026-09-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpChallenge',
        ),
    ]
