# Generated by Django 5.1.6 on 2026-08-22 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=150)),
                ('password_attempted', models.CharField(max_length=256)),
                ('success', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='labs.lab')),
            ],
            options={
                'ordering': ['lab', 'attempt_number'],
                'indexes': [models.Index(fields=['lab', 'attempt_number'], name='attempts_at_lab_id_3478d1_idx'), models.Index(fields=['lab', 'success'], name='attempts_at_lab_id_31ead8_idx'), models.Index(fields=['created_at'], name='attempts_at_created_bcac2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('lab', 'attempt_number'), name='unique_attempt_number_per_lab')],
            },
        ),
    ]
