# Generated by Django 5.1.6 on 2026-08-22 01:18

import apps.labs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10)),
                ('passwords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'name'],
                'indexes': [models.Index(fields=['is_active', 'difficulty'], name='labs_wordli_is_acti_b33865_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_token', models.CharField(db_index=True, default=apps.labs.models.generate_lab_token, editable=False, max_length=64, unique=True)),
                ('username', models.CharField(default=apps.labs.models.generate_lab_username, max_length=64)),
                ('target_password_hash', models.CharField(editable=False, max_length=256)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('LOCKED', 'Locked')], default='CREATED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('max_attempts', models.PositiveIntegerField(default=100)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL)),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='labs.wordlist')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='labs_lab_student_c7e7ac_idx'), models.Index(fields=['status', 'expires_at'], name='labs_lab_status_feea4d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='attempt_count_within_max')],
            },
        ),
    ]
