# Generated by Django 6.0.8 on 2026-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
