# Generated by Django 6.0.8 on 2026-09-14 15:20

import apps.challenge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('vault_id', models.CharField(max_length=32)),
                ('vault_password', models.CharField(max_length=64)),
                ('recovery_key', models.CharField(max_length=64)),
                ('vault_blob', models.JSONField(default=dict)),
                ('flag', models.CharField(default=apps.challenge.models.generate_flag, max_length=64, unique=True)),
                ('password_rotated', models.BooleanField(default=False)),
                ('rotated_password', models.CharField(blank=True, max_length=128)),
                ('cracked_login_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_data_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_password_at', models.DateTimeField(blank=True, null=True)),
                ('opened_vault_at', models.DateTimeField(blank=True, null=True)),
                ('captured_flag_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(fields=['assigned_to'], name='challenge_v_assigne_9d2f13_idx')],
            },
        ),
    ]
